import { Organization, QCFinding, QCRun, User } from "../types";

export const MOCK_USER: User = {
  id: "usr-01",
  email: "gogulnath@spandsons.com",
  full_name: "Gogulnath",
  role: "ENGINEER",
  organization_id: "org-spandsons-01",
};

export const MOCK_ORGANIZATION: Organization = {
  id: "org-spandsons-01",
  name: "Spandsons Horizon Engineering Pvt. Ltd.",
  slug: "spandsons-horizon",
  plan_tier: "ENTERPRISE",
  credits_remaining: 248,
};

export const MOCK_FINDINGS: QCFinding[] = [
  {
    id: "f-01",
    finding_code: "FIND-001",
    rule_id: "RULE-WIRE-001",
    category: "WIRE_SIZING",
    description: "Wire Run W102 connected to Circuit Breaker CB-101 is missing its wire gauge specification.",
    severity: "CRITICAL",
    confidence_level: "HIGH",
    confidence_score: 0.985,
    page_number: 1,
    location_bbox: {
      x: 130,
      y: 195,
      width: 190,
      height: 70,
    },
    evidence_text: "Line 24: CB-101 (20A) -> [W102 / BLK] -> J101:Pin1 (Missing AWG callout)",
    requirement_text: "All current-carrying conductors must have an explicit gauge callout sized to circuit breaker rating.",
    standard_citation: "IPC-WHMA-A-620D §13.4.1 (Conductor Sizing & Protection)",
    recommendation: "Specify minimum 12 AWG (or MIL-W-22759/16-12) to satisfy the 20A continuous load rating of CB-101.",
    feedback_status: undefined,
  },
  {
    id: "f-02",
    finding_code: "FIND-002",
    rule_id: "RULE-CONN-002",
    category: "CONNECTOR_PINOUT",
    description: "Pin gauge mismatch between Connector J101 (Pin 4, 20AWG) and Mating Plug P101 (Pin 4, 16AWG).",
    severity: "MAJOR",
    confidence_level: "HIGH",
    confidence_score: 0.942,
    page_number: 1,
    location_bbox: {
      x: 440,
      y: 155,
      width: 200,
      height: 80,
    },
    evidence_text: "Schematic J101:Pin4 listed as 20AWG signal line; Mating Assembly P101 Pin 4 specified as 16AWG power contact.",
    requirement_text: "Mating contact pin gauges and current ratings must match across disconnect interfaces.",
    standard_citation: "IPC-WHMA-A-620D §9.2.3 (Pin Contacts & Retention)",
    recommendation: "Reconcile connector pin contact sizes to 20AWG or insert step-down adapter contact.",
    feedback_status: undefined,
  },
  {
    id: "f-03",
    finding_code: "FIND-003",
    rule_id: "RULE-BEND-001",
    category: "HARNESS_ROUTING",
    description: "Insufficient bend radius indicated for shielded coaxial cable bundle HV-BUNDLE-A near chassis bulkhead.",
    severity: "MAJOR",
    confidence_level: "MEDIUM",
    confidence_score: 0.884,
    page_number: 1,
    location_bbox: {
      x: 345,
      y: 345,
      width: 195,
      height: 85,
    },
    evidence_text: "Bend radius annotated as R12mm on outer bundle diameter OD=8mm (Ratio = 1.5x)",
    requirement_text: "Shielded harness bend radius must not be less than 6x outer diameter (minimum R48mm required).",
    standard_citation: "IPC-WHMA-A-620D §13.1.2 (Minimum Bend Radius Standards)",
    recommendation: "Increase bend radius relief to at least R50mm or install 90-degree connector backshell.",
    feedback_status: undefined,
  },
  {
    id: "f-04",
    finding_code: "FIND-004",
    rule_id: "RULE-COLOR-003",
    category: "COLOR_CODING",
    description: "Non-standard wire insulation color (Orange) used for AC grounded neutral return path.",
    severity: "MINOR",
    confidence_level: "HIGH",
    confidence_score: 0.967,
    page_number: 1,
    location_bbox: {
      x: 125,
      y: 435,
      width: 205,
      height: 65,
    },
    evidence_text: "Wire W204: [ORG] designated as AC NEUTRAL BUS (N) return.",
    requirement_text: "Grounded AC neutral conductor insulation must be continuous White, Natural Gray, or three white stripes.",
    standard_citation: "UL 508A Table 28.1 (Industrial Control Panel Wire Color Identification)",
    recommendation: "Change wire insulation color from Orange to White (WHT) or Light Blue (BLU for CE compliance).",
    feedback_status: undefined,
  },
  {
    id: "f-05",
    finding_code: "FIND-005",
    rule_id: "RULE-TERM-004",
    category: "TERMINATIONS",
    description: "Terminal block Lug-T4 missing fastening torque specification callout on primary 24V busbar.",
    severity: "MINOR",
    confidence_level: "HIGH",
    confidence_score: 0.921,
    page_number: 1,
    location_bbox: {
      x: 665,
      y: 315,
      width: 175,
      height: 75,
    },
    evidence_text: "Lug-T4 bolted connection to BUS-24V has no torque footnote annotation.",
    requirement_text: "All field and factory screw-type terminal connections must indicate prescribed tightening torque (N·m / in-lb).",
    standard_citation: "UL 508A §29.3 (Torque Markings for Electrical Connectors)",
    recommendation: "Add general note or callout: 'TORQUE LUG-T4 TO 4.5 N·m (40 in-lb)'.",
    feedback_status: undefined,
  },
  {
    id: "f-06",
    finding_code: "FIND-006",
    rule_id: "RULE-REV-005",
    category: "DESIGNATORS",
    description: "Reference designator prefix 'RLY-1' deviates from standard aerospace schematic format 'K1'.",
    severity: "INFO",
    confidence_level: "HIGH",
    confidence_score: 0.991,
    page_number: 1,
    location_bbox: {
      x: 655,
      y: 165,
      width: 165,
      height: 70,
    },
    evidence_text: "Component labeled RLY-1 for 28VDC Auxiliary Bus Contactor.",
    requirement_text: "Electromechanical relays and contactors should use class designator 'K' per standard.",
    standard_citation: "MIL-STD-12D & IEEE 315 §22.2 (Reference Designators for Electrical Parts)",
    recommendation: "Update schematic designator to 'K101' for consistency across project drawing sets.",
    feedback_status: undefined,
  },
];

export const MOCK_QC_RUN: QCRun = {
  id: "run-spandsons-demo-01",
  organization_id: "org-spandsons-01",
  document_id: "doc-harness-777x",
  document_name: "Boeing_777X_Avionics_Harness_WD-777-04.pdf",
  overall_status: "FAIL",
  checks_total: 48,
  checks_passed: 42,
  checks_failed: 4,
  checks_review: 2,
  model_version: "qc-hybrid-engine-v1.0",
  prompt_version: "wiring-qc-prompt-v1.0",
  rules_version: "ruleset-ipc620-ul508a-v1.0",
  processing_time_ms: 1840,
  created_at: "2026-09-25T14:30:00Z",
  findings: MOCK_FINDINGS,
};

export const MOCK_RECENT_RUNS: QCRun[] = [
  MOCK_QC_RUN,
  {
    id: "run-abb-ctrl-02",
    organization_id: "org-spandsons-01",
    document_id: "doc-abb-400",
    document_name: "ABB_Series_400_Motor_Control_Panel_Sch.pdf",
    overall_status: "PASS",
    checks_total: 56,
    checks_passed: 56,
    checks_failed: 0,
    checks_review: 0,
    model_version: "qc-hybrid-engine-v1.0",
    prompt_version: "wiring-qc-prompt-v1.0",
    rules_version: "ruleset-ipc620-ul508a-v1.0",
    processing_time_ms: 1620,
    created_at: "2026-09-24T11:20:00Z",
    findings: [],
  },
  {
    id: "run-siemens-s7-03",
    organization_id: "org-spandsons-01",
    document_id: "doc-siemens-s7",
    document_name: "Siemens_S7-1500_PLC_Rack_Interconnect_RevB.pdf",
    overall_status: "REVIEW_REQUIRED",
    checks_total: 62,
    checks_passed: 59,
    checks_failed: 1,
    checks_review: 2,
    model_version: "qc-hybrid-engine-v1.0",
    prompt_version: "wiring-qc-prompt-v1.0",
    rules_version: "ruleset-ipc620-ul508a-v1.0",
    processing_time_ms: 2110,
    created_at: "2026-09-23T09:45:00Z",
    findings: [MOCK_FINDINGS[2], MOCK_FINDINGS[4]],
  },
  {
    id: "run-honeywell-apu-04",
    organization_id: "org-spandsons-01",
    document_id: "doc-honeywell-apu",
    document_name: "Honeywell_APU_Controller_Wiring_Rev3.pdf",
    overall_status: "PASS",
    checks_total: 39,
    checks_passed: 39,
    checks_failed: 0,
    checks_review: 0,
    model_version: "qc-hybrid-engine-v1.0",
    prompt_version: "wiring-qc-prompt-v1.0",
    rules_version: "ruleset-ipc620-ul508a-v1.0",
    processing_time_ms: 1450,
    created_at: "2026-09-22T16:10:00Z",
    findings: [],
  },
];

export const MOCK_STANDARDS = [
  {
    id: "ipc-whma-a-620d",
    code: "IPC-WHMA-A-620D",
    name: "Requirements and Acceptance for Cable and Wire Harness Assemblies",
    revision: "Revision D (Class 3 Aerospace)",
    ruleCount: 38,
    active: true,
    category: "Aerospace / Defense",
  },
  {
    id: "ul-508a",
    code: "UL 508A",
    name: "Standard for Industrial Control Panels",
    revision: "3rd Edition",
    ruleCount: 26,
    active: true,
    category: "Industrial Power",
  },
  {
    id: "mil-std-681d",
    code: "MIL-STD-681D",
    name: "Identification Coding and Application of Hookup and Lead Wires",
    revision: "Notice 2",
    ruleCount: 14,
    active: true,
    category: "Military / Defense",
  },
  {
    id: "iso-20653",
    code: "ISO 20653",
    name: "Road Vehicles — Degrees of Protection (IP-Code) for Electrical Equipment",
    revision: "2013 Edition",
    ruleCount: 8,
    active: false,
    category: "Automotive",
  },
];
